# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from quorum.v1 import auth_pb2 as quorum_dot_v1_dot_auth__pb2


class AuthServiceStub:
    """AuthService handles login, logout, and the E2EE identity-key directory.
    Login is the only RPC in the system that does not require a bearer token.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/quorum.v1.AuthService/Login',
                request_serializer=quorum_dot_v1_dot_auth__pb2.LoginRequest.SerializeToString,
                response_deserializer=quorum_dot_v1_dot_auth__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/quorum.v1.AuthService/Logout',
                request_serializer=quorum_dot_v1_dot_auth__pb2.LogoutRequest.SerializeToString,
                response_deserializer=quorum_dot_v1_dot_auth__pb2.LogoutResponse.FromString,
                _registered_method=True)
        self.ChangePassword = channel.unary_unary(
                '/quorum.v1.AuthService/ChangePassword',
                request_serializer=quorum_dot_v1_dot_auth__pb2.ChangePasswordRequest.SerializeToString,
                response_deserializer=quorum_dot_v1_dot_auth__pb2.ChangePasswordResponse.FromString,
                _registered_method=True)
        self.WhoAmI = channel.unary_unary(
                '/quorum.v1.AuthService/WhoAmI',
                request_serializer=quorum_dot_v1_dot_auth__pb2.WhoAmIRequest.SerializeToString,
                response_deserializer=quorum_dot_v1_dot_auth__pb2.WhoAmIResponse.FromString,
                _registered_method=True)
        self.PublishIdentityKey = channel.unary_unary(
                '/quorum.v1.AuthService/PublishIdentityKey',
                request_serializer=quorum_dot_v1_dot_auth__pb2.PublishIdentityKeyRequest.SerializeToString,
                response_deserializer=quorum_dot_v1_dot_auth__pb2.PublishIdentityKeyResponse.FromString,
                _registered_method=True)
        self.GetIdentityKey = channel.unary_unary(
                '/quorum.v1.AuthService/GetIdentityKey',
                request_serializer=quorum_dot_v1_dot_auth__pb2.GetIdentityKeyRequest.SerializeToString,
                response_deserializer=quorum_dot_v1_dot_auth__pb2.GetIdentityKeyResponse.FromString,
                _registered_method=True)


class AuthServiceServicer:
    """AuthService handles login, logout, and the E2EE identity-key directory.
    Login is the only RPC in the system that does not require a bearer token.
    """

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangePassword(self, request, context):
        """ChangePassword lets the authenticated caller replace their own password,
        proving ownership with the current one. Self-service counterpart to the
        admin-only AdminService.ResetPassword.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WhoAmI(self, request, context):
        """WhoAmI resolves the caller's identity from their bearer token (used
        by bots, which authenticate with a token instead of Login).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishIdentityKey(self, request, context):
        """PublishIdentityKey registers the caller's long-term X25519 public key
        so other users can look it up to establish E2EE sessions.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIdentityKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=quorum_dot_v1_dot_auth__pb2.LoginRequest.FromString,
                    response_serializer=quorum_dot_v1_dot_auth__pb2.LoginResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=quorum_dot_v1_dot_auth__pb2.LogoutRequest.FromString,
                    response_serializer=quorum_dot_v1_dot_auth__pb2.LogoutResponse.SerializeToString,
            ),
            'ChangePassword': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangePassword,
                    request_deserializer=quorum_dot_v1_dot_auth__pb2.ChangePasswordRequest.FromString,
                    response_serializer=quorum_dot_v1_dot_auth__pb2.ChangePasswordResponse.SerializeToString,
            ),
            'WhoAmI': grpc.unary_unary_rpc_method_handler(
                    servicer.WhoAmI,
                    request_deserializer=quorum_dot_v1_dot_auth__pb2.WhoAmIRequest.FromString,
                    response_serializer=quorum_dot_v1_dot_auth__pb2.WhoAmIResponse.SerializeToString,
            ),
            'PublishIdentityKey': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishIdentityKey,
                    request_deserializer=quorum_dot_v1_dot_auth__pb2.PublishIdentityKeyRequest.FromString,
                    response_serializer=quorum_dot_v1_dot_auth__pb2.PublishIdentityKeyResponse.SerializeToString,
            ),
            'GetIdentityKey': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIdentityKey,
                    request_deserializer=quorum_dot_v1_dot_auth__pb2.GetIdentityKeyRequest.FromString,
                    response_serializer=quorum_dot_v1_dot_auth__pb2.GetIdentityKeyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'quorum.v1.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('quorum.v1.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService:
    """AuthService handles login, logout, and the E2EE identity-key directory.
    Login is the only RPC in the system that does not require a bearer token.
    """

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quorum.v1.AuthService/Login',
            quorum_dot_v1_dot_auth__pb2.LoginRequest.SerializeToString,
            quorum_dot_v1_dot_auth__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quorum.v1.AuthService/Logout',
            quorum_dot_v1_dot_auth__pb2.LogoutRequest.SerializeToString,
            quorum_dot_v1_dot_auth__pb2.LogoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChangePassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quorum.v1.AuthService/ChangePassword',
            quorum_dot_v1_dot_auth__pb2.ChangePasswordRequest.SerializeToString,
            quorum_dot_v1_dot_auth__pb2.ChangePasswordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WhoAmI(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quorum.v1.AuthService/WhoAmI',
            quorum_dot_v1_dot_auth__pb2.WhoAmIRequest.SerializeToString,
            quorum_dot_v1_dot_auth__pb2.WhoAmIResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishIdentityKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quorum.v1.AuthService/PublishIdentityKey',
            quorum_dot_v1_dot_auth__pb2.PublishIdentityKeyRequest.SerializeToString,
            quorum_dot_v1_dot_auth__pb2.PublishIdentityKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIdentityKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quorum.v1.AuthService/GetIdentityKey',
            quorum_dot_v1_dot_auth__pb2.GetIdentityKeyRequest.SerializeToString,
            quorum_dot_v1_dot_auth__pb2.GetIdentityKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
