# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from quorum.v1 import chat_pb2 as quorum_dot_v1_dot_chat__pb2


class ChatServiceStub:
    """ChatService is the realtime core: unary sends plus a single
    server-streaming Subscribe that delivers all events to a client.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Subscribe = channel.unary_stream(
                '/quorum.v1.ChatService/Subscribe',
                request_serializer=quorum_dot_v1_dot_chat__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=quorum_dot_v1_dot_chat__pb2.ServerEvent.FromString,
                _registered_method=True)
        self.SendChannelMessage = channel.unary_unary(
                '/quorum.v1.ChatService/SendChannelMessage',
                request_serializer=quorum_dot_v1_dot_chat__pb2.SendChannelMessageRequest.SerializeToString,
                response_deserializer=quorum_dot_v1_dot_chat__pb2.SendChannelMessageResponse.FromString,
                _registered_method=True)
        self.CreateChannel = channel.unary_unary(
                '/quorum.v1.ChatService/CreateChannel',
                request_serializer=quorum_dot_v1_dot_chat__pb2.CreateChannelRequest.SerializeToString,
                response_deserializer=quorum_dot_v1_dot_chat__pb2.Channel.FromString,
                _registered_method=True)
        self.JoinChannel = channel.unary_unary(
                '/quorum.v1.ChatService/JoinChannel',
                request_serializer=quorum_dot_v1_dot_chat__pb2.JoinChannelRequest.SerializeToString,
                response_deserializer=quorum_dot_v1_dot_chat__pb2.JoinChannelResponse.FromString,
                _registered_method=True)
        self.LeaveChannel = channel.unary_unary(
                '/quorum.v1.ChatService/LeaveChannel',
                request_serializer=quorum_dot_v1_dot_chat__pb2.LeaveChannelRequest.SerializeToString,
                response_deserializer=quorum_dot_v1_dot_chat__pb2.LeaveChannelResponse.FromString,
                _registered_method=True)
        self.ListChannels = channel.unary_unary(
                '/quorum.v1.ChatService/ListChannels',
                request_serializer=quorum_dot_v1_dot_chat__pb2.ListChannelsRequest.SerializeToString,
                response_deserializer=quorum_dot_v1_dot_chat__pb2.ListChannelsResponse.FromString,
                _registered_method=True)
        self.GetChannelHistory = channel.unary_unary(
                '/quorum.v1.ChatService/GetChannelHistory',
                request_serializer=quorum_dot_v1_dot_chat__pb2.GetChannelHistoryRequest.SerializeToString,
                response_deserializer=quorum_dot_v1_dot_chat__pb2.GetChannelHistoryResponse.FromString,
                _registered_method=True)
        self.SearchChannelMessages = channel.unary_unary(
                '/quorum.v1.ChatService/SearchChannelMessages',
                request_serializer=quorum_dot_v1_dot_chat__pb2.SearchChannelMessagesRequest.SerializeToString,
                response_deserializer=quorum_dot_v1_dot_chat__pb2.SearchChannelMessagesResponse.FromString,
                _registered_method=True)
        self.ListUsers = channel.unary_unary(
                '/quorum.v1.ChatService/ListUsers',
                request_serializer=quorum_dot_v1_dot_chat__pb2.ListUsersRequest.SerializeToString,
                response_deserializer=quorum_dot_v1_dot_chat__pb2.ListUsersResponse.FromString,
                _registered_method=True)
        self.SendDirect = channel.unary_unary(
                '/quorum.v1.ChatService/SendDirect',
                request_serializer=quorum_dot_v1_dot_chat__pb2.SendDirectRequest.SerializeToString,
                response_deserializer=quorum_dot_v1_dot_chat__pb2.SendDirectResponse.FromString,
                _registered_method=True)
        self.RegisterCommands = channel.unary_unary(
                '/quorum.v1.ChatService/RegisterCommands',
                request_serializer=quorum_dot_v1_dot_chat__pb2.RegisterCommandsRequest.SerializeToString,
                response_deserializer=quorum_dot_v1_dot_chat__pb2.RegisterCommandsResponse.FromString,
                _registered_method=True)


class ChatServiceServicer:
    """ChatService is the realtime core: unary sends plus a single
    server-streaming Subscribe that delivers all events to a client.
    """

    def Subscribe(self, request, context):
        """Subscribe opens the realtime event stream. One active stream per user;
        a newer Subscribe replaces (kicks) the previous one.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendChannelMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateChannel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinChannel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LeaveChannel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListChannels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChannelHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchChannelMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendDirect(self, request, context):
        """SendDirect relays an opaque E2EE envelope to a connected recipient.
        The server never persists these and cannot read the payload.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterCommands(self, request, context):
        """RegisterCommands lets a bot declare its slash commands. Used only for
        /help discovery and duplicate warnings; routing is client-side.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=quorum_dot_v1_dot_chat__pb2.SubscribeRequest.FromString,
                    response_serializer=quorum_dot_v1_dot_chat__pb2.ServerEvent.SerializeToString,
            ),
            'SendChannelMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendChannelMessage,
                    request_deserializer=quorum_dot_v1_dot_chat__pb2.SendChannelMessageRequest.FromString,
                    response_serializer=quorum_dot_v1_dot_chat__pb2.SendChannelMessageResponse.SerializeToString,
            ),
            'CreateChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateChannel,
                    request_deserializer=quorum_dot_v1_dot_chat__pb2.CreateChannelRequest.FromString,
                    response_serializer=quorum_dot_v1_dot_chat__pb2.Channel.SerializeToString,
            ),
            'JoinChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinChannel,
                    request_deserializer=quorum_dot_v1_dot_chat__pb2.JoinChannelRequest.FromString,
                    response_serializer=quorum_dot_v1_dot_chat__pb2.JoinChannelResponse.SerializeToString,
            ),
            'LeaveChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.LeaveChannel,
                    request_deserializer=quorum_dot_v1_dot_chat__pb2.LeaveChannelRequest.FromString,
                    response_serializer=quorum_dot_v1_dot_chat__pb2.LeaveChannelResponse.SerializeToString,
            ),
            'ListChannels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListChannels,
                    request_deserializer=quorum_dot_v1_dot_chat__pb2.ListChannelsRequest.FromString,
                    response_serializer=quorum_dot_v1_dot_chat__pb2.ListChannelsResponse.SerializeToString,
            ),
            'GetChannelHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChannelHistory,
                    request_deserializer=quorum_dot_v1_dot_chat__pb2.GetChannelHistoryRequest.FromString,
                    response_serializer=quorum_dot_v1_dot_chat__pb2.GetChannelHistoryResponse.SerializeToString,
            ),
            'SearchChannelMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchChannelMessages,
                    request_deserializer=quorum_dot_v1_dot_chat__pb2.SearchChannelMessagesRequest.FromString,
                    response_serializer=quorum_dot_v1_dot_chat__pb2.SearchChannelMessagesResponse.SerializeToString,
            ),
            'ListUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUsers,
                    request_deserializer=quorum_dot_v1_dot_chat__pb2.ListUsersRequest.FromString,
                    response_serializer=quorum_dot_v1_dot_chat__pb2.ListUsersResponse.SerializeToString,
            ),
            'SendDirect': grpc.unary_unary_rpc_method_handler(
                    servicer.SendDirect,
                    request_deserializer=quorum_dot_v1_dot_chat__pb2.SendDirectRequest.FromString,
                    response_serializer=quorum_dot_v1_dot_chat__pb2.SendDirectResponse.SerializeToString,
            ),
            'RegisterCommands': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterCommands,
                    request_deserializer=quorum_dot_v1_dot_chat__pb2.RegisterCommandsRequest.FromString,
                    response_serializer=quorum_dot_v1_dot_chat__pb2.RegisterCommandsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'quorum.v1.ChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('quorum.v1.ChatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChatService:
    """ChatService is the realtime core: unary sends plus a single
    server-streaming Subscribe that delivers all events to a client.
    """

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/quorum.v1.ChatService/Subscribe',
            quorum_dot_v1_dot_chat__pb2.SubscribeRequest.SerializeToString,
            quorum_dot_v1_dot_chat__pb2.ServerEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendChannelMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quorum.v1.ChatService/SendChannelMessage',
            quorum_dot_v1_dot_chat__pb2.SendChannelMessageRequest.SerializeToString,
            quorum_dot_v1_dot_chat__pb2.SendChannelMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quorum.v1.ChatService/CreateChannel',
            quorum_dot_v1_dot_chat__pb2.CreateChannelRequest.SerializeToString,
            quorum_dot_v1_dot_chat__pb2.Channel.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JoinChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quorum.v1.ChatService/JoinChannel',
            quorum_dot_v1_dot_chat__pb2.JoinChannelRequest.SerializeToString,
            quorum_dot_v1_dot_chat__pb2.JoinChannelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LeaveChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quorum.v1.ChatService/LeaveChannel',
            quorum_dot_v1_dot_chat__pb2.LeaveChannelRequest.SerializeToString,
            quorum_dot_v1_dot_chat__pb2.LeaveChannelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListChannels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quorum.v1.ChatService/ListChannels',
            quorum_dot_v1_dot_chat__pb2.ListChannelsRequest.SerializeToString,
            quorum_dot_v1_dot_chat__pb2.ListChannelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChannelHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quorum.v1.ChatService/GetChannelHistory',
            quorum_dot_v1_dot_chat__pb2.GetChannelHistoryRequest.SerializeToString,
            quorum_dot_v1_dot_chat__pb2.GetChannelHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchChannelMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quorum.v1.ChatService/SearchChannelMessages',
            quorum_dot_v1_dot_chat__pb2.SearchChannelMessagesRequest.SerializeToString,
            quorum_dot_v1_dot_chat__pb2.SearchChannelMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quorum.v1.ChatService/ListUsers',
            quorum_dot_v1_dot_chat__pb2.ListUsersRequest.SerializeToString,
            quorum_dot_v1_dot_chat__pb2.ListUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendDirect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quorum.v1.ChatService/SendDirect',
            quorum_dot_v1_dot_chat__pb2.SendDirectRequest.SerializeToString,
            quorum_dot_v1_dot_chat__pb2.SendDirectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterCommands(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quorum.v1.ChatService/RegisterCommands',
            quorum_dot_v1_dot_chat__pb2.RegisterCommandsRequest.SerializeToString,
            quorum_dot_v1_dot_chat__pb2.RegisterCommandsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
